// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmgq7yEBDP-fnz9pZ__h2pptL4knUtbk',
    appId: '1:747752646321:web:916c9127241c3152922490',
    messagingSenderId: '747752646321',
    projectId: 'cashew-study-docs-3afed',
    authDomain: 'cashew-study-docs-3afed.firebaseapp.com',
    storageBucket: 'cashew-study-docs-3afed.firebasestorage.app',
    measurementId: 'G-CPL8LL8X5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSfbY1A54zL9tPg1sTfnjEGMBlvfrGJ3w',
    appId: '1:747752646321:android:1f3a908c3decbe8d922490',
    messagingSenderId: '747752646321',
    projectId: 'cashew-study-docs-3afed',
    storageBucket: 'cashew-study-docs-3afed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ZbX5wPsEZplFAkoEh5feGTa66C79UqQ',
    appId: '1:747752646321:ios:5fc852d7d3703354922490',
    messagingSenderId: '747752646321',
    projectId: 'cashew-study-docs-3afed',
    storageBucket: 'cashew-study-docs-3afed.firebasestorage.app',
    iosClientId: '747752646321-kg5qampf0vd63v3hha6sjk37st0em4il.apps.googleusercontent.com',
    iosBundleId: 'vn.edu.cashew.studyDocumentManager',
  );
}
