// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt8b_A1qE0puwlVP54e1IqHoFD4xYISVM',
    appId: '1:1047483797850:web:69e57b06c94780b5d7a363',
    messagingSenderId: '1047483797850',
    projectId: 'document-manager-e4289',
    authDomain: 'document-manager-e4289.firebaseapp.com',
    storageBucket: 'document-manager-e4289.firebasestorage.app',
    measurementId: 'G-VHZDN0RDX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5CnvMIZYeqe4SAYZVMQBir3omLDofZTc',
    appId: '1:1047483797850:android:c85776ddafcff074d7a363',
    messagingSenderId: '1047483797850',
    projectId: 'document-manager-e4289',
    storageBucket: 'document-manager-e4289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMt5INjGRQUlzAkmSTbluHz5asqXg23ro',
    appId: '1:1047483797850:ios:fb04674304b03a1bd7a363',
    messagingSenderId: '1047483797850',
    projectId: 'document-manager-e4289',
    storageBucket: 'document-manager-e4289.firebasestorage.app',
    iosBundleId: 'vn.edu.cashew.studyDocumentManager',
  );
}
