import 'package:budget/colors.dart';
import 'package:budget/database/tables.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

List<TransactionCategory> defaultCategories() {
  return [
    TransactionCategory(
      categoryPk: "1",
      name: "Học phí",
      colour: toHexString(Colors.blue),
      iconName: "graduation.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 0,
      income: false,
    ),
    TransactionCategory(
      categoryPk: "2",
      name: "Tiền thuê trọ",
      colour: toHexString(Colors.orange),
      iconName: "bills.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 1,
      income: false,
    ),
    TransactionCategory(
      categoryPk: "3",
      name: "Sách vở",
      colour: toHexString(Colors.indigo),
      iconName: "bookshelf.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 2,
      income: false,
    ),
    TransactionCategory(
      categoryPk: "4",
      name: "Đồ dùng học tập",
      colour: toHexString(Colors.teal),
      iconName: "shopping.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 3,
      income: false,
    ),
    TransactionCategory(
      categoryPk: "5",
      name: "Ăn uống",
      colour: toHexString(Colors.blueGrey),
      iconName: "cutlery.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 4,
      income: false,
    ),
    TransactionCategory(
      categoryPk: "6",
      name: "Đi lại",
      colour: toHexString(Colors.yellow),
      iconName: "tram.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 5,
      income: false,
    ),
    TransactionCategory(
      categoryPk: "7",
      name: "Giải trí",
      colour: toHexString(Colors.pink),
      iconName: "popcorn.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 6,
      income: false,
    ),
    TransactionCategory(
      categoryPk: "8",
      name: "Chi phí sinh hoạt khác",
      colour: toHexString(Colors.green),
      iconName: "groceries.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 7,
      income: false,
    ),
    TransactionCategory(
      categoryPk: "9",
      name: "Thu nhập",
      colour: toHexString(Colors.deepPurple.shade300),
      iconName: "coin.png",
      dateCreated: DateTime.now(),
      dateTimeModified: null,
      order: 8,
      income: true,
    ),
  ];
}
